syntax = "proto3";

option csharp_namespace = "AP_Theme_5.GrpcProtos";

package GrpcProtos;

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "variable.proto";
import "common.proto";

service AlarmConfiguration{
	rpc CreateAlarmConfiguration (CreateAlarmConfigurationRequest) returns (AlarmConfigurationDTO);
	rpc GetAlarmConfiguration (GetRequest) returns (NullableAlarmConfigurationDTO);
	rpc GetAllAlarmConfigurations (google.protobuf.Empty) returns (AlarmConfigurations);
	rpc UpdateAlarmConfiguration (AlarmConfigurationDTO) returns (google.protobuf.Empty);
	rpc DeleteAlarmConfiguration (DeleteRequest) returns (google.protobuf.Empty);
}

message AlarmConfigurationDTO{
	Priority priority = 1;
	double outofrange = 2;
	VariableDTO alarmvariable = 3;
}

message AlarmConfigurations{
	repeated AlarmConfigurationDTO items = 1;
}

message NullableAlarmConfigurationDTO{
	oneof kind{
		google.protobuf.NullValue null = 1;
		AlarmConfigurationDTO alarmconfiguration = 2;
	}
}

message CreateAlarmConfigurationRequest{
	double outofrange = 1;
	VariableDTO alarmvariable = 2;
}