syntax = "proto3";

option csharp_namespace = "AP_Theme_5.GrpcProtos";

package GrpcProtos;

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "common.proto";

service MeasurementUnit{
	rpc CreateMeasurementUnit (CreateMeasurementUnitRequest) returns (MeasurementUnitDTO);
	rpc GetMeasurementUnit (GetRequest) returns (NullableMeasurementUnitDTO);
	rpc GetAllMeasurementUnits (google.protobuf.Empty) returns (MeasurementUnits);
	rpc UpdateMeasurementUnit (MeasurementUnitDTO) returns (google.protobuf.Empty);
	rpc DeleteMeasurementUnit (DeleteRequest) returns (google.protobuf.Empty);
}

message MeasurementUnitDTO{
	string id = 1;
	string unittype = 2;
	string unitname = 3;
}

message MeasurementUnits{
	repeated MeasurementUnitDTO items = 1;
}

message NullableMeasurementUnitDTO{
	oneof kind{
		google.protobuf.NullValue null = 1;
		MeasurementUnitDTO MeasurementUnit = 2;
	}
}

message CreateMeasurementUnitRequest{
	string Unitname = 1;
	string Unittype =2;
}